# Generated by Django 4.2.7 on 2023-11-20 14:26

import AlbumApp_Django.web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), AlbumApp_Django.web.validators.validate_string_alphanumeric]),
        ),
    ]
